update readme and sphinx doc
s2mLab/pyScienceMode pull request #6
Opened 2023-11-22 15:49 UTC by benjicanal

2023-11-29 16:44 UTC, Kev1CO commented on pyScienceMode/acks.py
> +    Handles the errors of the Rehastim
Rehastim errors

2023-11-29 16:45 UTC, Kev1CO commented on pyScienceMode/acks.py
> +        Error code of the Rehastim
Rehastim code error

2023-11-29 16:48 UTC, Kev1CO commented on pyScienceMode/utils.py
> +# This code provides utility functions for working with the Rehastim device, including packet construction and data validation.
in """
"""
instead of #

2023-11-29 16:56 UTC, Kev1CO commented on docs/conf.py
> +author = "Ceglia, Co, Faresin"
order ?

2023-11-29 17:03 UTC, Kev1CO requested changes

2023-11-29 19:48 UTC, benjicanal commented on docs/about.rst
> +pyScienceMode is a python module to control the Rehastim2 and RehastimP24 devices from Hasomed.
Done.

2023-11-29 19:49 UTC, benjicanal commented on docs/index.rst
> +   example
Renamed in 'examples'

2023-11-29 19:50 UTC, benjicanal commented on pyScienceMode/acks.py
> +    Handles the errors of the Motomed
Done.

2023-11-29 19:50 UTC, benjicanal commented on pyScienceMode/acks.py
> +        Error code of the Motomed
Done.

2023-11-29 19:50 UTC, benjicanal commented on pyScienceMode/acks.py
> +    Handles the errors of the Rehastim
Done.

2023-11-29 19:51 UTC, benjicanal commented on pyScienceMode/acks.py
> +        Error code of the Rehastim
Done.

2023-11-29 19:52 UTC, benjicanal commented on pyScienceMode/acks.py
> +        Error code of the Rehastim
Done.

2023-11-29 19:53 UTC, benjicanal commented on pyScienceMode/utils.py
> +# This code provides utility functions for working with the Rehastim device, including packet construction and data validation.
Done.

2023-11-29 21:27 UTC, benjicanal commented on docs/main_differences.md
> +| Behavior when several channels are activated with too high frequency | The stimulator will stimulate at the maximum frequency to satisfy the offset between several channels. | Stimulation will not
Put a .png instead

2023-11-30 13:53 UTC, benjicanal commented on docs/contributing.rst
> +The easiest way to make sure black is happy is to locally run this command:
Done.

2023-12-05 20:14 UTC, merged